version: "1.0"
services:
  cole_fitness_be:
    build:
      context: .
      dockerfile: Dockerfile
    image: colefitness_be
    container_name: colefitness_be
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: [python, main.py]
